# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/american_date/all/american_date.rbi
#
# american_date-1.3.0

class Date
  def self._parse_without_american_date(*arg0); end
  def self.convert_american_to_iso(string); end
  def self.parse_without_american_date(*arg0); end
end
class DateTime < Date
  def self.parse_without_american_date(*arg0); end
end
