# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `image_processing` gem.
# Please instead update this file by running `bin/tapioca gem image_processing`.


# pkg:gem/image_processing#lib/image_processing/chainable.rb:1
module ImageProcessing
  class << self
    # Whether calling +name+ on +receiver+ would dispatch to an unsafe Ruby core
    # method rather than a genuine operation. Used as a single, shared guard at
    # every place where a user-provided name is dispatched via +public_send+.
    #
    # pkg:gem/image_processing#lib/image_processing.rb:21
    def unsafe_method?(receiver, name); end
  end
end

# pkg:gem/image_processing#lib/image_processing/builder.rb:2
class ImageProcessing::Builder
  include ::ImageProcessing::Chainable

  # pkg:gem/image_processing#lib/image_processing/builder.rb:7
  def initialize(options); end

  # Calls the pipeline to perform the processing from built options.
  #
  # pkg:gem/image_processing#lib/image_processing/builder.rb:12
  def call!(**call_options); end

  # pkg:gem/image_processing#lib/image_processing/builder.rb:5
  def options; end

  private

  # pkg:gem/image_processing#lib/image_processing/builder.rb:20
  def instrument; end

  # pkg:gem/image_processing#lib/image_processing/builder.rb:28
  def pipeline_options; end
end

# Implements a chainable interface for building processing options.
#
# pkg:gem/image_processing#lib/image_processing/chainable.rb:3
module ImageProcessing::Chainable
  # Add multiple operations as a hash or an array.
  #
  #   .apply(resize_to_limit: [400, 400], strip: true)
  #   # or
  #   .apply([[:resize_to_limit, [400, 400]], [:strip, true])
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:34
  def apply(operations); end

  # Creates a new builder object, merging current options with new options.
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:68
  def branch(**new_options); end

  # Call the defined processing and get the result. Allows specifying
  # the source file and destination.
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:59
  def call(file = T.unsafe(nil), destination: T.unsafe(nil), **call_options); end

  # Specify the output format.
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:10
  def convert(format); end

  # Register instrumentation block that will be called around the pipeline.
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:25
  def instrumenter(&block); end

  # Specify processor options applied when loading the image.
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:15
  def loader(**options); end

  # Add an operation defined by the processor.
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:53
  def operation(name, *args, &block); end

  # Specify processor options applied when saving the image.
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:20
  def saver(**options); end

  # Specify the source image file.
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:5
  def source(file); end

  private

  # This prevents calling unsafe Ruby core methods such as `Kernel#system`,
  # which would allow for remote shell execution. The processor enforces the
  # same guard when operations are dispatched, which also covers paths that
  # bypass this early check (e.g. the #operation meta-builder).
  #
  # Bang names are rejected here because they are Chainable's execution
  # shortcut (see #method_missing), not operations to chain.
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:95
  def invalid_operation?(name); end

  # Assume that any unknown method names an operation supported by the
  # processor. Add a bang ("!") if you want processing to be performed.
  #
  # pkg:gem/image_processing#lib/image_processing/chainable.rb:101
  def method_missing(name, *_arg1, **_arg2, &_arg3); end
end

# Empty options which the builder starts with.
#
# pkg:gem/image_processing#lib/image_processing/chainable.rb:109
ImageProcessing::Chainable::DEFAULT_OPTIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/image_processing#lib/image_processing.rb:8
class ImageProcessing::Error < ::StandardError; end

# pkg:gem/image_processing#lib/image_processing/pipeline.rb:4
class ImageProcessing::Pipeline
  # Initializes the pipeline with all the processing options.
  #
  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:10
  def initialize(options); end

  # Determines the destination and calls the processor.
  #
  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:19
  def call(save: T.unsafe(nil)); end

  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:7
  def destination; end

  # Determines the appropriate destination image format.
  #
  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:39
  def destination_format; end

  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:7
  def format; end

  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:7
  def loader; end

  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:7
  def operations; end

  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:7
  def processor; end

  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:7
  def saver; end

  # Retrieves the source path on disk.
  #
  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:34
  def source_path; end

  private

  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:49
  def call_processor(**options); end

  # Creates a new tempfile for the destination file, yields it, and refreshes
  # the file descriptor to get the updated file.
  #
  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:61
  def create_tempfile; end

  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:97
  def determine_format(file_path); end

  # In case of processing errors, both libvips and imagemagick will leave the
  # empty destination file they created, so this method makes sure it is
  # deleted in case an exception is raised on saving the image.
  #
  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:76
  def handle_destination; end

  # Converts the source image object into a path or the accumulator object.
  #
  # pkg:gem/image_processing#lib/image_processing/pipeline.rb:85
  def source; end
end

# pkg:gem/image_processing#lib/image_processing/pipeline.rb:5
ImageProcessing::Pipeline::DEFAULT_FORMAT = T.let(T.unsafe(nil), String)

# Abstract class inherited by individual processors.
#
# pkg:gem/image_processing#lib/image_processing/processor.rb:3
class ImageProcessing::Processor
  # pkg:gem/image_processing#lib/image_processing/processor.rb:47
  def initialize(accumulator = T.unsafe(nil)); end

  # Calls the operation to perform the processing. If the operation is
  # defined on the processor (macro), calls the method. Otherwise calls the
  # operation directly on the accumulator object. This provides a common
  # umbrella above defined macros and direct operations.
  #
  # pkg:gem/image_processing#lib/image_processing/processor.rb:55
  def apply_operation(name, *args, &block); end

  # Calls the given block with the accumulator object. Useful for when you
  # want to access the accumulator object directly.
  #
  # pkg:gem/image_processing#lib/image_processing/processor.rb:77
  def custom(&block); end

  class << self
    # Use for processor subclasses to specify the name and the class of their
    # accumulator object (e.g. MiniMagick::Tool or Vips::Image).
    #
    # pkg:gem/image_processing#lib/image_processing/processor.rb:31
    def accumulator(name, klass); end

    # Delegates to #apply_operation.
    #
    # pkg:gem/image_processing#lib/image_processing/processor.rb:38
    def apply_operation(accumulator, _arg1); end

    # pkg:gem/image_processing#lib/image_processing/processor.rb:4
    def call(source:, loader:, operations:, saver:, destination: T.unsafe(nil)); end

    # Whether the processor supports resizing the image upon loading.
    #
    # pkg:gem/image_processing#lib/image_processing/processor.rb:43
    def supports_resize_on_load?; end
  end
end

# Method owners considered unsafe to dispatch to when a method name comes
# from user input, because they expose Ruby's metaprogramming and shell
# primitives (e.g. Kernel#send, Kernel#eval, BasicObject#instance_eval,
# Kernel#system). Any name whose implementation is inherited from one of
# these should never be treated as an image operation or a loader/saver
# option.
#
# pkg:gem/image_processing#lib/image_processing.rb:16
ImageProcessing::UNSAFE_METHOD_OWNERS = T.let(T.unsafe(nil), Array)

# pkg:gem/image_processing#lib/image_processing/version.rb:2
ImageProcessing::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/image_processing#lib/image_processing/vips.rb:11
module ImageProcessing::Vips
  extend ::ImageProcessing::Chainable

  class << self
    # Returns whether the given image file is processable.
    #
    # pkg:gem/image_processing#lib/image_processing/vips.rb:15
    def valid_image?(file); end
  end
end

# pkg:gem/image_processing#lib/image_processing/vips.rb:22
class ImageProcessing::Vips::Processor < ::ImageProcessing::Processor
  # Overlays the specified image over the current one. Supports specifying
  # composite mode, direction or offset of the overlay image.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:126
  def composite(overlay, _mode = T.unsafe(nil), mode: T.unsafe(nil), gravity: T.unsafe(nil), offset: T.unsafe(nil), **options); end

  # pkg:gem/image_processing#lib/image_processing/vips.rb:156
  def remove(*args); end

  # Resizes the image to fit within the specified dimensions and fills
  # the remaining area with the specified background color.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:91
  def resize_and_pad(width, height, gravity: T.unsafe(nil), extend: T.unsafe(nil), background: T.unsafe(nil), alpha: T.unsafe(nil), **options); end

  # Resizes the image to cover the specified dimensions, without
  # cropping the excess.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:99
  def resize_to_cover(width, height, **options); end

  # Resizes the image to fill the specified dimensions, applying any
  # necessary cropping.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:85
  def resize_to_fill(width, height, **options); end

  # Resizes the image to fit within the specified dimensions.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:78
  def resize_to_fit(width, height, **options); end

  # Resizes the image to not be larger than the specified dimensions.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:72
  def resize_to_limit(width, height, **options); end

  # Rotates the image by an arbitrary angle.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:115
  def rotate(degrees, **options); end

  # make metadata setter methods chainable
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:153
  def set(*args); end

  # pkg:gem/image_processing#lib/image_processing/vips.rb:154
  def set_type(*args); end

  # pkg:gem/image_processing#lib/image_processing/vips.rb:155
  def set_value(*args); end

  protected

  # pkg:gem/image_processing#lib/image_processing/vips.rb:23
  def image; end

  private

  # Converts the image on disk in various forms into a Vips::Image object.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:190
  def convert_to_image(object, name); end

  # Hack to allow omitting one dimension.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:183
  def default_dimensions(width, height); end

  # Resizes the image according to the specified parameters, and sharpens
  # the resulting thumbnail.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:162
  def thumbnail(width, height, sharpen: T.unsafe(nil), **options); end

  class << self
    # Loads the image on disk into a Vips::Image object. Accepts additional
    # loader-specific options (e.g. interlacing). Afterwards auto-rotates the
    # image to be upright.
    #
    # pkg:gem/image_processing#lib/image_processing/vips.rb:34
    def load_image(path_or_image, loader: T.unsafe(nil), autorot: T.unsafe(nil), **options); end

    # Writes the Vips::Image object to disk. This starts the processing
    # pipeline defined in the Vips::Image object. Accepts additional
    # saver-specific options (e.g. quality).
    #
    # pkg:gem/image_processing#lib/image_processing/vips.rb:60
    def save_image(image, path, saver: T.unsafe(nil), quality: T.unsafe(nil), **options); end

    # See #thumbnail.
    #
    # pkg:gem/image_processing#lib/image_processing/vips.rb:53
    def supports_resize_on_load?; end
  end
end

# pkg:gem/image_processing#lib/image_processing/processor.rb:34
ImageProcessing::Vips::Processor::ACCUMULATOR_CLASS = Vips::Image

# Default sharpening mask that provides a fast and mild sharpen.
#
# pkg:gem/image_processing#lib/image_processing/vips.rb:26
ImageProcessing::Vips::Processor::SHARPEN_MASK = T.let(T.unsafe(nil), Vips::Image)

# pkg:gem/image_processing#lib/image_processing/vips.rb:206
module ImageProcessing::Vips::Processor::Utils
  private

  # libvips uses various loaders depending on the input format.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:210
  def select_valid_loader_options(source_path, options); end

  # libvips uses various loaders and savers depending on the input and
  # output image format. Each of these loaders and savers accept slightly
  # different options, so to allow the user to be able to specify options
  # for a specific loader/saver and have it ignored for other
  # loaders/savers, we do some introspection and filter out options that
  # don't exist for a particular loader or saver.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:227
  def select_valid_options(operation_name, options); end

  # Filters out unknown options for saving images.
  #
  # pkg:gem/image_processing#lib/image_processing/vips.rb:216
  def select_valid_saver_options(destination_path, options); end

  class << self
    # libvips uses various loaders depending on the input format.
    #
    # pkg:gem/image_processing#lib/image_processing/vips.rb:210
    def select_valid_loader_options(source_path, options); end

    # libvips uses various loaders and savers depending on the input and
    # output image format. Each of these loaders and savers accept slightly
    # different options, so to allow the user to be able to specify options
    # for a specific loader/saver and have it ignored for other
    # loaders/savers, we do some introspection and filter out options that
    # don't exist for a particular loader or saver.
    #
    # pkg:gem/image_processing#lib/image_processing/vips.rb:227
    def select_valid_options(operation_name, options); end

    # Filters out unknown options for saving images.
    #
    # pkg:gem/image_processing#lib/image_processing/vips.rb:216
    def select_valid_saver_options(destination_path, options); end
  end
end
