# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth-rails_csrf_protection` gem.
# Please instead update this file by running `bin/tapioca gem omniauth-rails_csrf_protection`.


# source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/version.rb#1
module OmniAuth; end

# source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/version.rb#2
module OmniAuth::RailsCsrfProtection; end

# source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/railtie.rb#6
class OmniAuth::RailsCsrfProtection::Railtie < ::Rails::Railtie; end

# Provides a callable method that verifies Cross-Site Request Forgery
# protection token. This class includes
# `ActionController::RequestForgeryProtection` directly and utilizes
# `verified_request?` method to match the way Rails performs token
# verification in Rails controllers.
#
# If you like to learn more about how Rails generate and verify
# authenticity token, you can find the source code at
# https://github.com/rails/rails/blob/v5.2.2/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L217-L240.
#
# source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#19
class OmniAuth::RailsCsrfProtection::TokenVerifier
  include ::ActiveSupport::Configurable
  include ::AbstractController::Helpers
  include ::ActiveSupport::Callbacks
  include ::AbstractController::Callbacks
  include ::ActionController::RequestForgeryProtection
  extend ::ActiveSupport::Configurable::ClassMethods
  extend ::AbstractController::Helpers::Resolution
  extend ::AbstractController::Helpers::ClassMethods
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::AbstractController::Callbacks::ClassMethods
  extend ::ActionController::RequestForgeryProtection::ClassMethods

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def __callbacks; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#54
  def _call(env); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def _helper_methods; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def _helper_methods=(_arg0); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def _helper_methods?; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def _process_action_callbacks; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def _run_process_action_callbacks(&block); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def allow_forgery_protection; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def allow_forgery_protection=(value); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#50
  def call(env); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def csrf_token_storage_strategy; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def csrf_token_storage_strategy=(value); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def forgery_protection_origin_check; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def forgery_protection_origin_check=(value); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def forgery_protection_strategy; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def forgery_protection_strategy=(value); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def log_warning_on_csrf_failure; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def log_warning_on_csrf_failure=(value); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#65
  def params(*_arg0, **_arg1, &_arg2); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def per_form_csrf_tokens; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def per_form_csrf_tokens=(value); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def raise_on_missing_callback_actions; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def raise_on_missing_callback_actions=(val); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def request_forgery_protection_token; end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def request_forgery_protection_token=(value); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#65
  def session(*_arg0, **_arg1, &_arg2); end

  private

  # Returns the value of attribute request.
  #
  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#64
  def request; end

  class << self
    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def __callbacks; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def __callbacks=(value); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def _helper_methods; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def _helper_methods=(value); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def _helper_methods?; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def _helpers; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def _process_action_callbacks; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def _process_action_callbacks=(value); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def allow_forgery_protection; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def allow_forgery_protection=(value); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def csrf_token_storage_strategy; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def csrf_token_storage_strategy=(value); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def forgery_protection_origin_check; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def forgery_protection_origin_check=(value); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def forgery_protection_strategy; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def forgery_protection_strategy=(value); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def log_warning_on_csrf_failure; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def log_warning_on_csrf_failure=(value); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def per_form_csrf_tokens; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def per_form_csrf_tokens=(value); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def raise_on_missing_callback_actions; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def raise_on_missing_callback_actions=(val); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def request_forgery_protection_token; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def request_forgery_protection_token=(value); end

    private

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def __class_attr___callbacks; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def __class_attr___callbacks=(new_value); end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def __class_attr__helper_methods; end

    # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
    def __class_attr__helper_methods=(new_value); end
  end
end

# source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
module OmniAuth::RailsCsrfProtection::TokenVerifier::HelperMethods
  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def form_authenticity_token(*_arg0, **_arg1, &_arg2); end

  # source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/token_verifier.rb#48
  def protect_against_forgery?(*_arg0, **_arg1, &_arg2); end
end

# source://omniauth-rails_csrf_protection//lib/omniauth/rails_csrf_protection/version.rb#3
OmniAuth::RailsCsrfProtection::VERSION = T.let(T.unsafe(nil), String)
