# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth-openid` gem.
# Please instead update this file by running `bin/tapioca gem omniauth-openid`.


# source://omniauth-openid//lib/omniauth/openid/version.rb#1
module OmniAuth
  class << self
    # source://omniauth/2.1.3/lib/omniauth.rb#134
    def config; end

    # source://omniauth/2.1.3/lib/omniauth.rb#138
    def configure; end

    # source://omniauth/2.1.3/lib/omniauth.rb#142
    def logger; end

    # source://omniauth/2.1.3/lib/omniauth.rb#146
    def mock_auth_for(provider); end

    # source://omniauth/2.1.3/lib/omniauth.rb#24
    def strategies; end
  end
end

# source://omniauth-openid//lib/omniauth/openid/version.rb#2
module OmniAuth::OpenID
  include ::OmniAuth::OpenID::Version
end

# source://omniauth-openid//lib/omniauth/openid/version.rb#3
module OmniAuth::OpenID::Version
  extend ::VersionGem::Basic
  extend ::VersionGem::Api
end

# source://omniauth-openid//lib/omniauth/openid/version.rb#4
OmniAuth::OpenID::Version::VERSION = T.let(T.unsafe(nil), String)

# source://omniauth-openid//lib/omniauth/strategies/open_id.rb#6
module OmniAuth::Strategies; end

# OmniAuth strategy for connecting via OpenID. This allows for connection
# to a wide variety of sites, some of which are listed [on the OpenID website](http://openid.net/get-an-openid/).
#
# source://omniauth-openid//lib/omniauth/strategies/open_id.rb#9
class OmniAuth::Strategies::OpenID
  include ::OmniAuth::Strategy
  extend ::OmniAuth::Strategy::ClassMethods

  # source://omniauth-openid//lib/omniauth/strategies/open_id.rb#129
  def ax_user_info; end

  # source://omniauth-openid//lib/omniauth/strategies/open_id.rb#104
  def callback_phase; end

  # source://omniauth-openid//lib/omniauth/strategies/open_id.rb#34
  def dummy_app; end

  # source://omniauth-openid//lib/omniauth/strategies/open_id.rb#87
  def get_identifier; end

  # source://omniauth-openid//lib/omniauth/strategies/open_id.rb#66
  def identifier; end

  # source://omniauth-openid//lib/omniauth/strategies/open_id.rb#109
  def openid_response; end

  # source://omniauth-openid//lib/omniauth/strategies/open_id.rb#72
  def request_phase; end

  # source://omniauth-openid//lib/omniauth/strategies/open_id.rb#118
  def sreg_user_info; end

  # source://omniauth-openid//lib/omniauth/strategies/open_id.rb#76
  def start; end
end

# source://omniauth-openid//lib/omniauth/strategies/open_id.rb#12
OmniAuth::Strategies::OpenID::AX = T.let(T.unsafe(nil), Hash)
