# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-httpx` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-httpx`.


# OpenTelemetry is an open source observability framework, providing a
# general-purpose API, SDK, and related tools required for the instrumentation
# of cloud-native software, frameworks, and libraries.
#
# The OpenTelemetry module provides global accessors for telemetry objects.
# See the documentation for the `opentelemetry-api` gem for details.
#
# source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry; end

# Instrumentation should be able to handle the case when the library is not installed on a user's system.
#
# source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation.rb#15
module OpenTelemetry::Instrumentation; end

# Contains the OpenTelemetry instrumentation for the Http gem
#
# source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx.rb#13
module OpenTelemetry::Instrumentation::HTTPX; end

# Utility module for normalizing HTTP methods according to OpenTelemetry semantic conventions
#
# @api private
#
# source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#12
module OpenTelemetry::Instrumentation::HTTPX::HttpHelper
  class << self
    # Prepares span data using both old and stable semantic conventions
    #
    # @api private
    # @param method [String, Symbol] The HTTP method
    # @return [SpanCreationAttributes] struct containing span_name and attributes hash
    #
    # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#107
    def span_attrs_for_dup(method); end

    # Prepares span data using old semantic conventions
    #
    # @api private
    # @param method [String, Symbol] The HTTP method
    # @return [SpanCreationAttributes] struct containing span_name and attributes hash
    #
    # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#58
    def span_attrs_for_old(method); end

    # Prepares span data using stable semantic conventions
    #
    # @api private
    # @param method [String, Symbol] The HTTP method
    # @return [SpanCreationAttributes] struct containing span_name and attributes hash
    #
    # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#80
    def span_attrs_for_stable(method); end
  end
end

# Pre-computed mapping to avoid string allocations during normalization
#
# @api private
#
# source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#17
OpenTelemetry::Instrumentation::HTTPX::HttpHelper::METHOD_CACHE = T.let(T.unsafe(nil), Hash)

# @api private
#
# source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#49
OpenTelemetry::Instrumentation::HTTPX::HttpHelper::OLD_SPAN_NAMES_BY_METHOD = T.let(T.unsafe(nil), Hash)

# Lightweight struct to hold span creation attributes
#
# @api private
#
# source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#14
class OpenTelemetry::Instrumentation::HTTPX::HttpHelper::SpanCreationAttributes < ::Struct
  # Returns the value of attribute attributes
  #
  # @return [Object] the current value of attributes
  #
  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#14
  def attributes; end

  # Sets the attribute attributes
  #
  # @param value [Object] the value to set the attribute attributes to.
  # @return [Object] the newly set value
  #
  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#14
  def attributes=(_); end

  # Returns the value of attribute span_name
  #
  # @return [Object] the current value of span_name
  #
  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#14
  def span_name; end

  # Sets the attribute span_name
  #
  # @param value [Object] the value to set the attribute span_name to.
  # @return [Object] the newly set value
  #
  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#14
  def span_name=(_); end

  class << self
    # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#14
    def [](*_arg0); end

    # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#14
    def inspect; end

    # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#14
    def keyword_init?; end

    # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#14
    def members; end

    # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/http_helper.rb#14
    def new(*_arg0); end
  end
end

# The Instrumentation class contains logic to detect and install the Http instrumentation
#
# source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/instrumentation.rb#11
class OpenTelemetry::Instrumentation::HTTPX::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/instrumentation.rb#28
  def determine_semconv; end

  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/instrumentation.rb#55
  def patch_dup; end

  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/instrumentation.rb#41
  def patch_old; end

  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/instrumentation.rb#48
  def patch_stable; end

  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/instrumentation.rb#70
  def require_dependencies_dup; end

  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/instrumentation.rb#62
  def require_dependencies_old; end

  # source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/instrumentation.rb#66
  def require_dependencies_stable; end
end

# source://opentelemetry-instrumentation-httpx//lib/opentelemetry/instrumentation/httpx/version.rb#10
OpenTelemetry::Instrumentation::HTTPX::VERSION = T.let(T.unsafe(nil), String)
