# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-grpc` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-grpc`.


# OpenTelemetry is an open source observability framework, providing a
# general-purpose API, SDK, and related tools required for the instrumentation
# of cloud-native software, frameworks, and libraries.
#
# The OpenTelemetry module provides global accessors for telemetry objects.
# See the documentation for the `opentelemetry-api` gem for details.
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
#
# pkg:gem/opentelemetry-instrumentation-grpc#lib/opentelemetry/instrumentation.rb:13
module OpenTelemetry; end

# "Instrumentation" are specified by
# https://github.com/open-telemetry/opentelemetry-specification/blob/784635d01d8690c8f5fcd1f55bdbc8a13cf2f4f2/specification/glossary.md#instrumentation-library
#
# Instrumentation should be able to handle the case when the library is not installed on a user's system.
#
# pkg:gem/opentelemetry-instrumentation-grpc#lib/opentelemetry/instrumentation.rb:18
module OpenTelemetry::Instrumentation; end

# Contains the OpenTelemetry instrumentation for the gRPC gem
#
# pkg:gem/opentelemetry-instrumentation-grpc#lib/opentelemetry/instrumentation/grpc.rb:13
module OpenTelemetry::Instrumentation::Grpc; end

# pkg:gem/opentelemetry-instrumentation-grpc#lib/opentelemetry/instrumentation/grpc.rb:14
class OpenTelemetry::Instrumentation::Grpc::Error < ::StandardError; end

# The Instrumentation class contains logic to detect and install the Grpc instrumentation
#
# pkg:gem/opentelemetry-instrumentation-grpc#lib/opentelemetry/instrumentation/grpc/instrumentation.rb:11
class OpenTelemetry::Instrumentation::Grpc::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # pkg:gem/opentelemetry-instrumentation-grpc#lib/opentelemetry/instrumentation/grpc/instrumentation.rb:26
  def patch; end

  # pkg:gem/opentelemetry-instrumentation-grpc#lib/opentelemetry/instrumentation/grpc/instrumentation.rb:30
  def require_dependencies; end
end

# pkg:gem/opentelemetry-instrumentation-grpc#lib/opentelemetry/instrumentation/grpc/version.rb:10
OpenTelemetry::Instrumentation::Grpc::VERSION = T.let(T.unsafe(nil), String)
