# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-all` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-all`.


# OpenTelemetry is an open source observability framework, providing a
# general-purpose API, SDK, and related tools required for the instrumentation
# of cloud-native software, frameworks, and libraries.
#
# The OpenTelemetry module provides global accessors for telemetry objects.
# See the documentation for the `opentelemetry-api` gem for details.
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
#
# pkg:gem/opentelemetry-instrumentation-all#lib/opentelemetry/instrumentation/all.rb:58
module OpenTelemetry; end

# pkg:gem/opentelemetry-instrumentation-all#lib/opentelemetry/instrumentation/all.rb:59
module OpenTelemetry::Instrumentation; end

# Namespace for the Opentelemetry all-in-one gem
#
# pkg:gem/opentelemetry-instrumentation-all#lib/opentelemetry/instrumentation/all.rb:61
module OpenTelemetry::Instrumentation::All; end

# pkg:gem/opentelemetry-instrumentation-all#lib/opentelemetry/instrumentation/all/version.rb:10
OpenTelemetry::Instrumentation::All::VERSION = T.let(T.unsafe(nil), String)
