# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-restclient` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-restclient`.


# OpenTelemetry is an open source observability framework, providing a
# general-purpose API, SDK, and related tools required for the instrumentation
# of cloud-native software, frameworks, and libraries.
#
# The OpenTelemetry module provides global accessors for telemetry objects.
# See the documentation for the `opentelemetry-api` gem for details.
#
# source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry; end

# "Instrumentation" are specified by
# https://github.com/open-telemetry/opentelemetry-specification/blob/784635d01d8690c8f5fcd1f55bdbc8a13cf2f4f2/specification/glossary.md#instrumentation-library
#
# Instrumentation should be able to handle the case when the library is not installed on a user's system.
#
# source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation.rb#18
module OpenTelemetry::Instrumentation; end

# Contains the OpenTelemetry instrumentation for the RestClient gem
#
# source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation/restclient.rb#13
module OpenTelemetry::Instrumentation::RestClient; end

# The Instrumentation class contains logic to detect and install the RestClient
# instrumentation
#
# source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation/restclient/instrumentation.rb#12
class OpenTelemetry::Instrumentation::RestClient::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation/restclient/instrumentation.rb#27
  def determine_semconv; end

  # source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation/restclient/instrumentation.rb#52
  def patch_request_dup; end

  # source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation/restclient/instrumentation.rb#60
  def patch_request_old; end

  # source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation/restclient/instrumentation.rb#56
  def patch_request_stable; end

  # source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation/restclient/instrumentation.rb#40
  def require_dependencies_dup; end

  # source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation/restclient/instrumentation.rb#48
  def require_dependencies_old; end

  # source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation/restclient/instrumentation.rb#44
  def require_dependencies_stable; end
end

# source://opentelemetry-instrumentation-restclient//lib/opentelemetry/instrumentation/restclient/version.rb#10
OpenTelemetry::Instrumentation::RestClient::VERSION = T.let(T.unsafe(nil), String)
