# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-exporter-otlp` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-exporter-otlp`.


# OpenTelemetry is an open source observability framework, providing a
# general-purpose API, SDK, and related tools required for the instrumentation
# of cloud-native software, frameworks, and libraries.
#
# The OpenTelemetry module provides global accessors for telemetry objects.
# See the documentation for the `opentelemetry-api` gem for details.
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
#
# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/version.rb:7
module OpenTelemetry; end

# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/version.rb:8
module OpenTelemetry::Exporter; end

# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/version.rb:9
module OpenTelemetry::Exporter::OTLP; end

# An OpenTelemetry trace exporter that sends spans over HTTP as Protobuf encoded OTLP ExportTraceServiceRequests.
#
# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:23
class OpenTelemetry::Exporter::OTLP::Exporter
  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:48
  def initialize(endpoint: T.unsafe(nil), certificate_file: T.unsafe(nil), client_certificate_file: T.unsafe(nil), client_key_file: T.unsafe(nil), ssl_verify_mode: T.unsafe(nil), headers: T.unsafe(nil), compression: T.unsafe(nil), timeout: T.unsafe(nil), metrics_reporter: T.unsafe(nil)); end

  # Called to export sampled {OpenTelemetry::SDK::Trace::SpanData} structs.
  #
  # @param [Enumerable<OpenTelemetry::SDK::Trace::SpanData>] span_data the
  #   list of recorded {OpenTelemetry::SDK::Trace::SpanData} structs to be
  #   exported.
  # @param [optional Numeric] timeout An optional timeout in seconds.
  # @return [Integer] the result of the export.
  #
  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:78
  def export(span_data, timeout: T.unsafe(nil)); end

  # Called when {OpenTelemetry::SDK::Trace::TracerProvider#force_flush} is called, if
  # this exporter is registered to a {OpenTelemetry::SDK::Trace::TracerProvider}
  # object.
  #
  # @param [optional Numeric] timeout An optional timeout in seconds.
  #
  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:89
  def force_flush(timeout: T.unsafe(nil)); end

  # Called when {OpenTelemetry::SDK::Trace::TracerProvider#shutdown} is called, if
  # this exporter is registered to a {OpenTelemetry::SDK::Trace::TracerProvider}
  # object.
  #
  # @param [optional Numeric] timeout An optional timeout in seconds.
  #
  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:98
  def shutdown(timeout: T.unsafe(nil)); end

  private

  # The around_request is a private method that provides an extension
  # point for the exporters network calls. The default behaviour
  # is to not trace these operations.
  #
  # An example use case would be to prepend a patch, or extend this class
  # and override this method's behaviour to explicitly trace the HTTP request.
  # This would allow you to trace your export pipeline.
  #
  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:144
  def around_request; end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:402
  def as_otlp_any_value(value); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:394
  def as_otlp_key_value(key, value); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:333
  def as_otlp_span(span_data); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:383
  def as_otlp_span_kind(kind); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:375
  def as_otlp_status_code(code); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:271
  def backoff?(retry_count:, reason:, retry_after: T.unsafe(nil)); end

  # Builds span flags based on whether the parent span context is remote.
  # This follows the OTLP specification for span flags.
  #
  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:108
  def build_span_flags(parent_span_is_remote, base_flags); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:297
  def encode(span_data); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:238
  def handle_redirect(location); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:126
  def http_connection(uri, ssl_verify_mode, certificate_file, client_certificate_file, client_key_file); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:253
  def log_request_failure(response_code); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:242
  def log_status(body); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:258
  def measure_request_duration; end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:448
  def parse_headers(raw); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:420
  def prepare_endpoint(endpoint); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:435
  def prepare_headers(config_headers); end

  # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:148
  def send_bytes(bytes, timeout:); end

  class << self
    # pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:38
    def ssl_verify_mode; end
  end
end

# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:36
OpenTelemetry::Exporter::OTLP::Exporter::DEFAULT_USER_AGENT = T.let(T.unsafe(nil), String)

# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:33
OpenTelemetry::Exporter::OTLP::Exporter::ERROR_MESSAGE_INVALID_HEADERS = T.let(T.unsafe(nil), String)

# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:25
OpenTelemetry::Exporter::OTLP::Exporter::FAILURE = T.let(T.unsafe(nil), Integer)

# Default timeouts in seconds.
#
# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:29
OpenTelemetry::Exporter::OTLP::Exporter::KEEP_ALIVE_TIMEOUT = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:30
OpenTelemetry::Exporter::OTLP::Exporter::RETRY_COUNT = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/exporter.rb:24
OpenTelemetry::Exporter::OTLP::Exporter::SUCCESS = T.let(T.unsafe(nil), Integer)

# Current OpenTelemetry OTLP exporter version
#
# pkg:gem/opentelemetry-exporter-otlp#lib/opentelemetry/exporter/otlp/version.rb:11
OpenTelemetry::Exporter::OTLP::VERSION = T.let(T.unsafe(nil), String)
