# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-grape` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-grape`.


# OpenTelemetry is an open source observability framework, providing a
# general-purpose API, SDK, and related tools required for the instrumentation
# of cloud-native software, frameworks, and libraries.
#
# The OpenTelemetry module provides global accessors for telemetry objects.
# See the documentation for the `opentelemetry-api` gem for details.
#
# source://opentelemetry-instrumentation-grape//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry; end

# Instrumentation should be able to handle the case when the library is not installed on a user's system.
#
# source://opentelemetry-instrumentation-grape//lib/opentelemetry/instrumentation.rb#15
module OpenTelemetry::Instrumentation; end

# Contains the OpenTelemetry instrumentation for the Grape gem
#
# source://opentelemetry-instrumentation-grape//lib/opentelemetry/instrumentation/grape.rb#13
module OpenTelemetry::Instrumentation::Grape; end

# The Instrumentation class contains logic to detect and install the Grape instrumentation
# # Configuration keys and options
# ## `:ignored_events`
#
# Default is `[]`. Specifies which ActiveSupport::Notifications events published by Grape to ignore.
# Ignored events will not be published as Span events.
#
# ## `:install_rack`
#
# Default is `true`. Specifies whether or not to install the Rack instrumentation as part of installing the Grape instrumentation.
# This is useful in cases where you have multiple Rack applications but want to manually specify where to insert the tracing middleware.
#
# source://opentelemetry-instrumentation-grape//lib/opentelemetry/instrumentation/grape/instrumentation.rb#21
class OpenTelemetry::Instrumentation::Grape::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-grape//lib/opentelemetry/instrumentation/grape/instrumentation.rb#44
  def gem_version; end

  # source://opentelemetry-instrumentation-grape//lib/opentelemetry/instrumentation/grape/instrumentation.rb#48
  def install_rack_instrumentation; end

  # source://opentelemetry-instrumentation-grape//lib/opentelemetry/instrumentation/grape/instrumentation.rb#54
  def require_dependencies; end

  # source://opentelemetry-instrumentation-grape//lib/opentelemetry/instrumentation/grape/instrumentation.rb#58
  def subscribe; end
end

# Minimum Grape version needed for compatibility with this instrumentation
#
# source://opentelemetry-instrumentation-grape//lib/opentelemetry/instrumentation/grape/instrumentation.rb#23
OpenTelemetry::Instrumentation::Grape::Instrumentation::MINIMUM_VERSION = T.let(T.unsafe(nil), Gem::Version)

# Current gem version
#
# source://opentelemetry-instrumentation-grape//lib/opentelemetry/instrumentation/grape/version.rb#11
OpenTelemetry::Instrumentation::Grape::VERSION = T.let(T.unsafe(nil), String)
