# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `popper_js` gem.
# Please instead update this file by running `bin/tapioca gem popper_js`.


# source://popper_js//lib/popper_js/version.rb#3
module PopperJs; end

# source://popper_js//lib/popper_js/engine.rb#4
class PopperJs::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.2.0/lib/active_support/callbacks.rb#70
    def __callbacks; end
  end
end

# source://popper_js//lib/popper_js/version.rb#4
PopperJs::VERSION = T.let(T.unsafe(nil), String)
