# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tidewave` gem.
# Please instead update this file by running `bin/tapioca gem tidewave`.


# pkg:gem/tidewave#lib/tidewave/version.rb:3
class Tidewave
  # pkg:gem/tidewave#lib/tidewave.rb:48
  def initialize(app, options = T.unsafe(nil)); end

  # pkg:gem/tidewave#lib/tidewave.rb:57
  def call(env); end

  private

  # pkg:gem/tidewave#lib/tidewave.rb:310
  def build_tool_registry; end

  # pkg:gem/tidewave#lib/tidewave.rb:127
  def config_data; end

  # pkg:gem/tidewave#lib/tidewave.rb:105
  def config_endpoint(_request); end

  # pkg:gem/tidewave#lib/tidewave.rb:142
  def forbidden(message); end

  # pkg:gem/tidewave#lib/tidewave.rb:217
  def handle_initialize(request_id, params); end

  # pkg:gem/tidewave#lib/tidewave.rb:188
  def handle_mcp_message(message); end

  # pkg:gem/tidewave#lib/tidewave.rb:240
  def handle_tool_call(request_id, params); end

  # pkg:gem/tidewave#lib/tidewave.rb:88
  def home_endpoint(_request); end

  # pkg:gem/tidewave#lib/tidewave.rb:137
  def json_response(payload, status: T.unsafe(nil)); end

  # pkg:gem/tidewave#lib/tidewave.rb:264
  def jsonrpc_error_response(request_id, code, message); end

  # pkg:gem/tidewave#lib/tidewave.rb:268
  def jsonrpc_error_response_body(request_id, code, message); end

  # pkg:gem/tidewave#lib/tidewave.rb:256
  def jsonrpc_success_response_body(request_id, result); end

  # pkg:gem/tidewave#lib/tidewave.rb:109
  def mcp_endpoint(request); end

  # pkg:gem/tidewave#lib/tidewave.rb:147
  def not_found; end

  # pkg:gem/tidewave#lib/tidewave.rb:155
  def response_headers(content_type, body); end

  # pkg:gem/tidewave#lib/tidewave.rb:82
  def strip_x_frame_options(response); end

  # pkg:gem/tidewave#lib/tidewave.rb:303
  def text_content(text); end

  # pkg:gem/tidewave#lib/tidewave.rb:151
  def text_response(status, message); end

  # pkg:gem/tidewave#lib/tidewave.rb:279
  def tool_definitions; end

  # pkg:gem/tidewave#lib/tidewave.rb:283
  def tool_error_result(message); end

  # pkg:gem/tidewave#lib/tidewave.rb:290
  def tool_result(result); end

  # pkg:gem/tidewave#lib/tidewave.rb:162
  def valid_client_ip?(request); end

  # pkg:gem/tidewave#lib/tidewave.rb:174
  def validate_jsonrpc_message(message); end
end

# pkg:gem/tidewave#lib/tidewave.rb:30
Tidewave::CONFIG_ROUTE = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave/configuration.rb:4
class Tidewave::Configuration
  # pkg:gem/tidewave#lib/tidewave/configuration.rb:7
  def initialize; end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def allow_remote_access; end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def allow_remote_access=(_arg0); end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def client_url; end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def client_url=(_arg0); end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def dev; end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def dev=(_arg0); end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def logger; end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def logger=(_arg0); end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def logger_middleware; end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def logger_middleware=(_arg0); end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def preferred_orm; end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def preferred_orm=(_arg0); end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def team; end

  # pkg:gem/tidewave#lib/tidewave/configuration.rb:5
  def team=(_arg0); end
end

# pkg:gem/tidewave#lib/tidewave.rb:41
Tidewave::DEFAULT_OPTIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/tidewave#lib/tidewave/database_adapter.rb:4
class Tidewave::DatabaseAdapter
  # pkg:gem/tidewave#lib/tidewave/database_adapter.rb:20
  def execute_query(query, arguments = T.unsafe(nil)); end

  # pkg:gem/tidewave#lib/tidewave/database_adapter.rb:24
  def get_models; end

  class << self
    # pkg:gem/tidewave#lib/tidewave/database_adapter.rb:6
    def for(orm_type); end
  end
end

# pkg:gem/tidewave#lib/tidewave.rb:12
module Tidewave::DatabaseAdapters; end

# pkg:gem/tidewave#lib/tidewave/exceptions_middleware.rb:3
class Tidewave::ExceptionsMiddleware
  # pkg:gem/tidewave#lib/tidewave/exceptions_middleware.rb:4
  def initialize(app); end

  # pkg:gem/tidewave#lib/tidewave/exceptions_middleware.rb:8
  def call(env); end

  private

  # pkg:gem/tidewave#lib/tidewave/exceptions_middleware.rb:70
  def append_body(body, headers, content); end

  # pkg:gem/tidewave#lib/tidewave/exceptions_middleware.rb:27
  def format_exception_html(exception, request); end

  # pkg:gem/tidewave#lib/tidewave/exceptions_middleware.rb:64
  def request_parameters(request); end
end

# pkg:gem/tidewave#lib/tidewave.rb:33
Tidewave::INVALID_IP = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave.rb:39
Tidewave::INVALID_ORIGIN = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave.rb:29
Tidewave::MCP_ROUTE = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave.rb:31
Tidewave::PROTOCOL_VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave/quiet_requests_middleware.rb:3
class Tidewave::QuietRequestsMiddleware
  # pkg:gem/tidewave#lib/tidewave/quiet_requests_middleware.rb:4
  def initialize(app); end

  # pkg:gem/tidewave#lib/tidewave/quiet_requests_middleware.rb:8
  def call(env); end
end

# pkg:gem/tidewave#lib/tidewave/railtie.rb:9
class Tidewave::Railtie < ::Rails::Railtie; end

# pkg:gem/tidewave#lib/tidewave.rb:28
Tidewave::TIDEWAVE_ROUTE = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave/tool.rb:4
class Tidewave::Tool
  # pkg:gem/tidewave#lib/tidewave/tool.rb:16
  def initialize(_options = T.unsafe(nil)); end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:23
  def call(_arguments = T.unsafe(nil)); end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:19
  def definition; end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:27
  def validate_and_call(arguments); end

  private

  # pkg:gem/tidewave#lib/tidewave/tool.rb:118
  def article_for(type); end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:114
  def property_path(path, name); end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:74
  def validate_array(value, schema, path); end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:122
  def validate_default(value, path); end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:57
  def validate_object(value, schema, path); end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:83
  def validate_required_properties(value, required_properties, path); end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:44
  def validate_schema(value, schema, path = T.unsafe(nil)); end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:91
  def validate_type(value, type, path); end

  # pkg:gem/tidewave#lib/tidewave/tool.rb:97
  def value_matches_type?(value, type); end

  class << self
    # pkg:gem/tidewave#lib/tidewave/tool.rb:6
    def descendants; end

    # pkg:gem/tidewave#lib/tidewave/tool.rb:10
    def inherited(subclass); end
  end
end

# pkg:gem/tidewave#lib/tidewave.rb:17
module Tidewave::Tools; end

# pkg:gem/tidewave#lib/tidewave/tools/execute_sql_query.rb:3
class Tidewave::Tools::ExecuteSqlQuery < ::Tidewave::Tool
  # pkg:gem/tidewave#lib/tidewave/tools/execute_sql_query.rb:19
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/tidewave#lib/tidewave/tools/execute_sql_query.rb:48
  def call(arguments_hash); end

  # pkg:gem/tidewave#lib/tidewave/tools/execute_sql_query.rb:23
  def definition; end
end

# pkg:gem/tidewave#lib/tidewave/tools/execute_sql_query.rb:4
Tidewave::Tools::ExecuteSqlQuery::DESCRIPTION = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave/tools/get_docs.rb:3
class Tidewave::Tools::GetDocs < ::Tidewave::Tool
  # pkg:gem/tidewave#lib/tidewave/tools/get_docs.rb:35
  def call(arguments); end

  # pkg:gem/tidewave#lib/tidewave/tools/get_docs.rb:17
  def definition; end

  private

  # pkg:gem/tidewave#lib/tidewave/tools/get_docs.rb:48
  def extract_documentation(file_path, line_number); end

  # pkg:gem/tidewave#lib/tidewave/tools/get_docs.rb:79
  def ignorable_comment?(comment); end
end

# pkg:gem/tidewave#lib/tidewave/tools/get_docs.rb:4
Tidewave::Tools::GetDocs::DESCRIPTION = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave/tools/get_logs.rb:5
class Tidewave::Tools::GetLogs < ::Tidewave::Tool
  # pkg:gem/tidewave#lib/tidewave/tools/get_logs.rb:12
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/tidewave#lib/tidewave/tools/get_logs.rb:43
  def call(arguments); end

  # pkg:gem/tidewave#lib/tidewave/tools/get_logs.rb:16
  def definition; end

  private

  # pkg:gem/tidewave#lib/tidewave/tools/get_logs.rb:63
  def tail_lines(file_path); end
end

# pkg:gem/tidewave#lib/tidewave/tools/get_logs.rb:6
Tidewave::Tools::GetLogs::DESCRIPTION = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave/tools/get_models.rb:5
class Tidewave::Tools::GetModels < ::Tidewave::Tool
  # pkg:gem/tidewave#lib/tidewave/tools/get_models.rb:10
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/tidewave#lib/tidewave/tools/get_models.rb:29
  def call(_arguments); end

  # pkg:gem/tidewave#lib/tidewave/tools/get_models.rb:16
  def definition; end

  private

  # pkg:gem/tidewave#lib/tidewave/tools/get_models.rb:47
  def get_relative_source_location(model_name); end
end

# pkg:gem/tidewave#lib/tidewave/tools/get_models.rb:6
Tidewave::Tools::GetModels::DESCRIPTION = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave/tools/get_source_location.rb:5
class Tidewave::Tools::GetSourceLocation < ::Tidewave::Tool
  # pkg:gem/tidewave#lib/tidewave/tools/get_source_location.rb:20
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/tidewave#lib/tidewave/tools/get_source_location.rb:42
  def call(arguments); end

  # pkg:gem/tidewave#lib/tidewave/tools/get_source_location.rb:24
  def definition; end

  private

  # pkg:gem/tidewave#lib/tidewave/tools/get_source_location.rb:78
  def format_source_location(file_path, line_number); end

  # pkg:gem/tidewave#lib/tidewave/tools/get_source_location.rb:85
  def get_package_location(package); end

  class << self
    # pkg:gem/tidewave#lib/tidewave/tools/get_source_location.rb:55
    def get_source_location(reference); end
  end
end

# pkg:gem/tidewave#lib/tidewave/tools/get_source_location.rb:6
Tidewave::Tools::GetSourceLocation::DESCRIPTION = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave/tools/project_eval.rb:7
class Tidewave::Tools::ProjectEval < ::Tidewave::Tool
  # pkg:gem/tidewave#lib/tidewave/tools/project_eval.rb:51
  def call(arguments_hash); end

  # pkg:gem/tidewave#lib/tidewave/tools/project_eval.rb:21
  def definition; end

  private

  # pkg:gem/tidewave#lib/tidewave/tools/project_eval.rb:113
  def eval_binding(arguments); end
end

# pkg:gem/tidewave#lib/tidewave/tools/project_eval.rb:19
Tidewave::Tools::ProjectEval::DEFAULT_TIMEOUT = T.let(T.unsafe(nil), Integer)

# pkg:gem/tidewave#lib/tidewave/tools/project_eval.rb:8
Tidewave::Tools::ProjectEval::DESCRIPTION = T.let(T.unsafe(nil), String)

# pkg:gem/tidewave#lib/tidewave/version.rb:4
Tidewave::VERSION = T.let(T.unsafe(nil), String)
