# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/will_paginate-bootstrap4/all/will_paginate-bootstrap4.rbi
#
# will_paginate-bootstrap4-0.2.2

module Bootstrap
end
module Bootstrap::WillPaginate
end
class Bootstrap::WillPaginate::Engine < Rails::Engine
end
