# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yaml` gem.
# Please instead update this file by running `bin/tapioca gem yaml`.


# pkg:gem/yaml#lib/yaml.rb:20
module Psych
  extend ::Bootsnap::CompileCache::YAML::Psych4::Patch
end

# pkg:gem/yaml#lib/yaml.rb:69
Psych::LOADER_VERSION = T.let(T.unsafe(nil), String)
