AllCops:
   SuggestExtensions: false

Lint/MixedRegexpCaptureTypes:
   Enabled: false

Style/Documentation:
   Enabled: false

Metrics/MethodLength:
   Enabled: false

Metrics/ClassLength:
   Enabled: false

Metrics/AbcSize:
   Enabled: false

Style/GlobalVars:
   Enabled: false

Style/FormatStringToken:
   Enabled: false

Layout/LineLength:
   Enabled: false
