language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.3.0
    #- rbx
    #- jruby-19mode
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database serveme_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - mkdir tmp/cache
  - mkdir public/uploads
script: ./script/ci
sudo: false
services:
  - memcached
  - redis-server
