language: ruby
cache: bundler
rvm:
  - 2.3.3
  - 2.4.0
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database serveme_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - mkdir tmp/cache
  - mkdir public/uploads
script: ./script/ci
sudo: false
services:
  - memcached
  - redis-server
