language: ruby
cache: bundler
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
bundler_args: --without development production
addons:
  postgresql: "9.6"
before_script:
  - cp config/database.yml.travis config/database.yml
  - mkdir tmp/cache
  - mkdir public/uploads
script:
  - bundle exec rails db:reset db:setup RAILS_ENV=test
  - ./script/ci
sudo: false
services:
  - postgresql
  - memcached
  - redis-server
