language: ruby
cache: bundler
rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.0
addons:
  postgresql: "9.3"
before_script:
  - git submodule update --init --recursive
  - git clone --recursive git://github.com/maxmind/libmaxminddb
  - cd libmaxminddb
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - psql -c 'create database serveme_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - mkdir tmp/cache
  - mkdir public/uploads
script: ./script/ci
services:
  - memcached
  - redis-server
