language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
    #- rbx
    #- jruby-19mode
before_script:
  - mysql -e 'create database serveme_test;'
  - mkdir tmp/cache
  - mkdir public/uploads
script: ./script/ci
sudo: false
