gem:
  # Add your `gem` command parameters here:
  #
  # exclude:
  # - gem_name
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
  exclude:
    - ActionMailbox::PipeCompiler # Doesn't work because of some classloading issue
  halt_upon_load_error: false
