development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379") %>
  channel_prefix: serveme_hotwire_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379") %>
  channel_prefix: serveme_hotwire_production
