---
league_maps:
- name: ETF2L 6v6
  active: true
  maps:
  - cp_granary_pro_rc17a3
  - cp_gullywash_f9
  - cp_metalworks_f7
  - cp_process_f12
  - cp_reckoner
  - cp_snakewater_final1
  - cp_sultry_b8a
  - cp_sunshine
  - cp_villa_b19
  - koth_bagel_rc11
  - koth_product_final
- name: ETF2L HL
  active: true
  maps:
  - cp_steel_f12
  - koth_ashville_final1
  - koth_product_final
  - pl_upward_f12
  - pl_vigil_rc10
- name: ETF2L Ultiduo
  active: true
  maps:
  - koth_ultiduo_r_b7
  - ultiduo_baloo_v2
  - ultiduo_grove_b4
  - ultiduo_lookout_b1
  - ultiduo_cooked_rc2
  - ultiduo_process_f10
  - ultiduo_babty_f3
- name: ozfortress Ultiduo
  active: true
  maps:
  - ultiduo_baloo_v2
  - ultiduo_champions_b1
  - ultiduo_ozf_r
  - ultiduo_swine_b06
- name: ozfortress 6v6
  active: true
  maps:
  - cp_granary_pro_rc17a3
  - cp_gullywash_f9
  - cp_metalworks_f7
  - cp_process_f12
  - cp_snakewater_final1
  - cp_sunshine
  - koth_bagel_rc11
  - koth_clearcut_b17
  - koth_product_final
- name: ozfortress HL
  active: true
  maps:
  - cp_steel_f12
  - koth_ashville_final1
  - koth_product_final
  - koth_proot_b6c-alt2
  - koth_proside_v1
  - pl_eruption_b14
  - pl_swiftwater_final1
  - pl_upward_f12
  - pl_vigil_rc10
- name: RGL 6v6
  active: true
  maps:
  - cp_granary_pro_rc17a3
  - cp_gullywash_f9
  - cp_metalworks_f7
  - cp_process_f12
  - cp_reckoner
  - cp_sunshine
  - koth_bagel_rc11
  - koth_clearcut_b18
- name: RGL HL
  active: true
  maps:
  - cp_nidal_b6
  - koth_ashville_final1
  - koth_lakeside_f5
  - koth_product_final
  - pl_swiftwater_final1
  - pl_upward_f12
  - pl_vigil_rc10
- name: RGL Pass Time
  active: true
  maps:
  - pass_arena2_b15
  - pass_boutique_rc5
  - pass_maple_a10
  - pass_plexiglass_b6
  - pass_ruin_a12_waterless
  - pass_stadium_rc4
  - pass_stonework_rc4
  - pass_torii_a8
- name: UGC 6v6
  active: true
  maps:
  - cp_granary_pro_rc16f
  - cp_metalworks_f7
  - cp_process_f12
  - cp_reckoner
  - cp_snakewater_final1
  - cp_sunshine
  - koth_bagel_rc11
  - koth_govan_b9
- name: UGC HL
  active: true
  maps:
  - cp_steel_f12
  - koth_ashville_final1
  - koth_proot_b5b
  - koth_warmtic_f10
  - pl_divulgence_b4b
  - pl_swiftwater_final1
  - pl_upward_f12
  - pl_vigil_rc10
- name: UGC 4v4
  active: true
  maps:
  - cp_gravelbine_a11
  - cp_warmfrost_rc1
  - koth_airfield_b7
  - koth_badlands
  - koth_bagel_rc11
  - koth_cornyard_b4
  - koth_jamram_rc2b
  - koth_maple_ridge_rc2
- name: UGC Ultiduo
  active: true
  maps:
  - ulti_fira_b2a
  - ultiduo_baloo_v2
  - ultiduo_furnace_b2
  - ultiduo_gullywash_b2
  - ultiduo_lookout_b1
  - ultiduo_noodle
  - ultiduo_obsidiian_a10
  - ultiduo_spytech_rc4
