development:
  mode: sandbox
  client_id: foo
  client_secret: bar
  rest_endpoint: https://api.sandbox.paypal.com

test:
  mode: sandbox
  client_id: foo
  client_secret: bar
  rest_endpoint: https://api.sandbox.paypal.com
