:schedule:
  clean_up:
    cron: "0 5 * * * Europe/Amsterdam"
    class: CleanupWorker

  minutely:
    cron: "* * * * * Europe/Amsterdam"
    class: "CronWorker"

  server_updates:
    cron: "* * * * * Europe/Amsterdam"
    class: "ServerUpdatesWorker"

  monthly_donations:
    cron: "15 2,21 * * * Europe/Amsterdam"
    class: "MonthlyDonationProgressAnnouncerWorker"

  private_server_cleanup:
    cron: "0 */6 * * * Europe/Amsterdam"
    class: "PrivateServerCleanupWorker"

  notifications:
    cron: "*/20 * * * * Europe/Amsterdam"
    class: "ServersNotificationWorker"
