---
address: 127.0.0.1
pid: tmp/pids/thin.pid
port: 3010
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
daemonize: true
chdir: /var/www/serveme/current
