#!/bin/bash
`echo "STEAM_WEB_API_KEY = 'foo'" > config/initializers/steam.rb`
export RAILS_ENV=test

./script/bundler

run() {
  echo "=== Running: $* ==="
  time bundle exec $*
}

run rake db:create db:migrate:reset
run rspec spec
