#!/bin/bash
export RAILS_ENV=test
export CUCUMBER_PUBLISH_QUIET=true

run() {
  time bundle exec $*
}

echo "--- Starting continuous integration build"

./script/bundler

echo "--- Migrate the database from scratch"

run rake db:environment:set db:migrate

if [[ -d coverage ]]; then
  echo "Removing old coverage report"
  rm -r coverage
fi

echo "--- Running RSpec and Cucumber ---"
run rake test_with_coveralls
