#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "csv"

APP_ROOT = File.expand_path("..", __dir__)

autocorrect = false

OptionParser.new do |parser|
  parser.banner = "Usage: script/sort_and_dedup_csv [options]"

  parser.on("-a", "--autocorrect", "Automatically fix sorting/deduplication") do
    autocorrect = true
  end
end.parse!

files = [ "banned_steam_ids.csv", "banned_ips.csv", "vpn_ips.csv", "whitelisted_steam_ids.csv", "whitelisted_ips.csv", "bad-asn-list.csv" ]
doc_dir = File.join(APP_ROOT, "doc")
files_modified = []

files.each do |file|
  file_path = File.join(doc_dir, file)
  next unless File.exist?(file_path)

  table = CSV.parse(File.read(file_path), headers: true)

  sorted_rows = if file == "bad-asn-list.csv"
    table.uniq { |r| r[0] }.sort_by { |r| [ r["ASN"].to_i, r["Entity"] ] }
  else
    table.uniq { |r| r[0] }.sort_by { |r| [ r["name"].downcase, r["reason"], r[0] ] }
  end

  current_content = File.read(file_path)
  csv_options = { write_headers: true, headers: table.headers }
  csv_options[:force_quotes] = true if file == "bad-asn-list.csv"

  new_content = CSV.generate(**csv_options) do |csv|
    sorted_rows.each do |r|
      csv << r
    end
  end

  if current_content != new_content
    files_modified << file
    if autocorrect
      File.write(file_path, new_content)
    end
  end
end

if files_modified.any? && !autocorrect
  warn "Files need sorting/deduplication: #{files_modified.join(', ')}"
  warn "Run with -a to automatically fix"
  exit 1
end
