name: Setup Ruby
description: Install Ruby from .tool-versions and install gems with bundler caching

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
      with:
        ruby-version: .tool-versions
        bundler-cache: true
