name: Setup Ruby
description: Install Ruby from .tool-versions and install gems with bundler caching

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
      with:
        ruby-version: .tool-versions
        bundler-cache: true
